server:
  port: 11000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

spring:
  application:
    name: configure-center
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
