server:
  port: 12000

spring:
  application:
    name: gateway-center
  cloud:
    config:
      profile: dev
      uri: http://localhost:11000/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
