server:
  port: 12000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

spring:
  application:
    name: @pom.artifactId@
  cloud:
    config:
      profile: dev
      uri: http://localhost:11000/
